### ISSUE TITLE
Silverlight vs WinRT

### ISSUE THREAD

**Issue by nishanthkarthik** [ShaastraWebops/WindowsApp#2]
We have two options for our app. I will mention the pros and cons of both.
## Silverlight

Shaastra 2015 Windows app was written in **Silverlight**. There were a lot of libraries at that time. Everything that would work on desktop WPF applications (a few exceptions) will work on Silverlight for Windows Phone. Almost every app in the store at that time was Silverlight, mostly a Pivot | Panorama | Single Paged app. While handling images, SL apps took too much RAM (We were inefficient in our code at that time). The animations would be laggy and mostly primitive UI controls was used. 
## WinRT

WinRT is new. **WinRT** can be ported to a metro app without much effort. Performance in handling images is better. The only issues are the lack of too many libraries, even though the most used libraries of SL are available for WinRT. Windows 10 is on its way, with desktop RTM on July 29. The Mobile edition will be a couple of months after that. So, coding on WinRT will give us expertise in switching to Windows 10 UAP. Windows 10 UAP is basically a superset of WinRT APIs, which in turn are close to metal. Also, with the presence of .NET native using which we can compile c# apps to native ARM code that can run on phones, it is worth it to take up WinRT this year.

I vote for WinRT, but would like to hear all of your thoughts, 
@akhilsathuluri 
@rdarpan 
@etchandgear 
@blackViking007.

**Comment by GIT-chandra** [comment]
I think WinRT would be good.

**Comment by nishanthkarthik** [comment]
Lets meet tomorrow for a coding session. We will meet at CFI at 10.00AM. Does anyone have any issues?

Karthik Nishanth
Sent from my Windows Phone

**Comment by akhilsathuluri** [comment]
Is it possible to shift it to some time in the evening like even 3 or 4 is fine. We are having an industrial visit planned tomorrow. 
- Akhil Sathuluri 
  Sent from my Windows Phone. 

-----Original Message-----

**Comment by nishanthkarthik** [comment]
3PM onwards then..

Sent from my Windows Phone

**Comment by rdarpan** [comment]
i dont think i can come even then tomorrow... i will come to insti @
probably 3pm..not sure

On 11 September 2015 at 13:16, Karthik Nishanth notifications@github.com
wrote:

> 3PM onwards then..
> 
> Sent from my Windows Phone
> 
> ---
> 
> From: akhilsathulurimailto:notifications@github.com
> Sent: ‎9/‎11/‎2015 11:46 AM
> To: ShaastraWebops/WindowsAppmailto:WindowsApp@noreply.github.com
> Cc: Karthik Nishanthmailto:nishanthkarthik@live.com
> Subject: Re: [WindowsApp] Silverlight vs WinRT (#2)
> 
> Is it possible to shift it to some time in the evening like even 3 or 4 is
> fine. We are having an industrial visit planned tomorrow.
> - Akhil Sathuluri
>   Sent from my Windows Phone.
> 
> -----Original Message-----
> From: "Karthik Nishanth" notifications@github.com
> Sent: ‎11/‎09/‎2015 11:20
> To: "ShaastraWebops/WindowsApp" WindowsApp@noreply.github.com
> Cc: "akhilsathuluri" akhilsathuluri@gmail.com
> Subject: Re: [WindowsApp] Silverlight vs WinRT (#2)
> 
> Lets meet tomorrow for a coding session. We will meet at CFI at 10.00AM.
> Does anyone have any issues?
> 
> Karthik Nishanth
> Sent from my Windows Phone
> 
> ---
> 
> From: etchandgearmailto:notifications@github.com
> Sent: ‎6/‎24/‎2015 2:17 PM
> To: ShaastraWebops/WindowsAppmailto:WindowsApp@noreply.github.com
> Cc: Karthik Nishanthmailto:nishanthkarthik@live.com
> Subject: Re: [WindowsApp] Silverlight vs WinRT (#2)
> 
> I think WinRT would be good.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ShaastraWebops/WindowsApp/issues/2#issuecomment-114791293
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ShaastraWebops/WindowsApp/issues/2#issuecomment-139462245
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShaastraWebops/WindowsApp/issues/2#issuecomment-139476117
> .

## 

M Rakshith Darpan
Undergraduate Student
Department of Engineering Design
Indian Institute of Technology Madras
Chennai-600036

**Comment by akhilsathuluri** [comment]
Works fine for me. 😊 
- Akhil Sathuluri 
  Sent from my Windows Phone. 

-----Original Message-----

**Comment by GIT-chandra** [comment]
Is it going to be a long session? Because I'm planning on participating in
a hackathon that starts from 11 am tomorrow.

**Comment by nishanthkarthik** [comment]
It is, since we actually haven't started anything at all.

Sent from my Windows Phone

**Comment by nishanthkarthik** [comment]
If anyone has win10 mobile, can he build the apk from android repo and put it in his Windows 10 Mobile - Project Astoria emulator? It would help us in getting some idea about what android has done...

**Comment by GIT-chandra** [comment]
Can we have it some other time? There's a Programming Club session from
3:30 till 5:30 and I really want to attend it.

On Fri, Sep 11, 2015 at 10:09 PM, Karthik Nishanth <notifications@github.com

**Comment by nishanthkarthik** [comment]
Sure, you tell me the time.

Sent from my Windows Phone

**Comment by GIT-chandra** [comment]
5:30?

**Comment by nishanthkarthik** [comment]
Sure
