### ISSUE TITLE
Team meet for Windows

### ISSUE THREAD

**Issue by nishanthkarthik** [ShaastraWebops/WindowsApp#3]
Hello @akhilsathuluri 
@rdarpan 
@etchandgear 
@blackViking007 

We will meet tonight at 09.00 PM for discussing about Windows app, probably at one of our rooms.
Please acknowledge this message in the same page.

**Comment by hrshptl6595** [comment]
Ok....
My room can be used for the meeting if its not a problem for everyone.....
Room no.: 249, Mandak....

-----Original Message-----

**Comment by rdarpan** [comment]
Acknowledged

M Rakshith Darpan
2nd Year Undergraduate
Dept. of Engineering Design
IIT Madras

**Comment by GIT-chandra** [comment]
Acknowledged.

**Comment by hrshptl6595** [comment]
Is everyone okay with coming to my room for the meeting????

-----Original Message-----

**Comment by akhilsathuluri** [comment]
Acknowledged
- Akhil Sathuluri 
  Sent from my Windows Phone. 

-----Original Message-----

**Comment by nishanthkarthik** [comment]
If it keeps drizzling, shall we meet tomorrow? What say?

**Comment by hrshptl6595** [comment]
It's fine but if we can have the meeting today, it will be good.....

-----Original Message-----

**Comment by akhilsathuluri** [comment]
Yeah its actually raining. So even I prefer to meet tomorrow. 
- Akhil Sathuluri 
  Sent from my Windows Phone. 

-----Original Message-----

**Comment by akhilsathuluri** [comment]
Can you please change the time of meeting I mean can you move it an hour or so further and make it 10. 
- Akhil Sathuluri 
  Sent from my Windows Phone. 

-----Original Message-----

**Comment by hrshptl6595** [comment]
Ok fine....
We can meet tomorrow at the same time.....

-----Original Message-----

**Comment by hrshptl6595** [comment]
Ok....
It's fine with me to have the meeting at 10 if everyone agrees......
Please do acknowledge.....

-----Original Message-----

**Comment by akhilsathuluri** [comment]
Acknowledged
- Akhil Sathuluri 
  Sent from my Windows Phone. 

-----Original Message-----

**Comment by rdarpan** [comment]
Acknowledged

M Rakshith Darpan
2nd Year Undergraduate
Dept. of Engineering Design
IIT Madras
