### ISSUE TITLE
Meeting on 4th October

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/WindowsApp#6]
Hello all,
I want to meet the whole windows team on 4th October i.e tomorrow.
Time 10 am
Venue CFI

Please acknowledge.

**Comment by GIT-chandra** [comment]
Acknowledged.

**Comment by akhilsathuluri** [comment]
Acknowledged !

**Comment by rdarpan** [comment]
Acknowledged

M Rakshith Darpan
3rd Year Undergraduate
Dept. of Engineering Design
IIT Madras
