### ISSUE TITLE
Meeting on 7th October

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/WindowsApp#9]
Reminder for the same.
Time 10pm, CFI

**Comment by chinnichaitanya** [comment]
Ok. Since many couldn't come tonight, lets shift this meeting to Friday.

**Comment by chinnichaitanya** [comment]
Reminder for the meeting.

**Comment by nishanthkarthik** [comment]
Is it 10pm, CFI today?

**Comment by chinnichaitanya** [comment]
Yes.

**Comment by akhilsathuluri** [comment]
I am sorry I wont be coming. Please mail me my work for the next deadline.
The registration page as such is done. I dont know how to work on the
splash screen after registration is done as in the android counterpart,
suggest me for a go on this.
